Format 35

Style Structure
  Category          MainText
  KeepEmpty         1
  LatexType         Command
  LatexName         structure
  Margin            First_Dynamic
  OptionalArgs      0
  NextNoIndent      1
  ParSkip           0
  TopSep            0.7
  BottomSep         0.7
  ParSep            0
  Align             Left
  AlignPossible    Block, Left, Right, Center
  LabelType         No_Label
  Font
    Color          Blue
  EndFont
 End

InsetLayout Flex:TextboxTikz
  Lyxtype charstyle
  LabelString TextboxTikz
  LatexType        command
  LatexName        textboxTikz
  Font
    Color          red
  EndFont
End
    