% fonts properties
iFontSize      = 20;
strFontUnit    = 'points'; % [{points} | normalized | inches | centimeters | pixels]
strFontName    = 'Times';  % [Times | Courier | ]                 TODO complete the list
strFontWeight  = 'normal'; % [light | {normal} | demi | bold]
strFontAngle   = 'normal'; % [{normal} | italic | oblique]     ps: only for axes 
strInterpreter = 'latex';  % [{tex} | latex | none]


% note: the xPosition and yPosition are referred in the "axes" units of measure
text(   xPosition,                       ...
        yPosition,                       ...
        'this is the text plotted',      ...
        'FontName',     strFontName,     ...
        'FontSize',     iFontSize,       ...
        'FontWeight',   strFontWeight,   ...
        'Interpreter',  strInterpreter);

