# -*- org -*-

# Time-stamp: <2011-11-04 18:35:15 Friday by lian>

#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

** Install
  - Under Windowns: Download from www.lyx.org/download directly
  - Under Linux: sudo apt-get install lyx (not recommand, because new version is not always available)
  - Compile from the source code: Strongly recommanded, compile nearly all the version of lyx in all linux distributions (e.g. ubuntu, fedora). I have tested the compiling even under ubuntu hardy 8.04, older LTS version. It worked perfectly.
    
** Tips
  1. Compile lyx
     - please refer to compile_lyx.sh
  2. Spell Checkers
     - ispell, aspell, hunspell.
     - hunspell is the most useful of the three checkers
     - if hunspell is not always available, e.g. ubuntu hardy, hunspell version in apt-get is too old to pass the compiliation of lyx 2.00. If in your apt-get, you can install the version >= hunspell 1.2.12, then you do not need to compile the hunspell yourself. otherwise, you need to compile hunspell yourself. then the lyx 2.00 can be compiled with hunspell spell checker.
  3. How to compile the hunspell?
     1) download the hunspell from http://sourceforge.net/projects/hunspell/files/Hunspell/
     2) extracing and then going to that directory
     3) please install stow for manage your own installed packages. sudo apt-get install stow
     4) ./configure && make install -j 2 && sudo make install prefix=/usr/local/stow/hunspell
     5) cd /usr/local/stow && sudo stow hunspell
     6) now you can try to launch hunspell by typing hunspell in your terminal
     7) if you get an error, possible reason could be that /usr/local/lib is not included by dynamic library manger, so please run the command ldconfig to solve the issue.
  4. Dictionaries of spellcheckers and thesaurus
     1) in my lian-dot-lyx directory, you can find the hunspell and thesaurus
     2) in lyx, Tools->Preferences->Path, you can set the paths of hunspell and thesaurus
        
        
** Graphics in Lyx/Latex
   1. Direct Graphics Image
      - Vectorized: eps,svg,pdf,wmf
      - Rasterized: png,bmp,jpeg
   2. Latex Code
      - Tikz/Pgf: support pdflatex and beamer, thus being the most popular between functionality and compatibility
      - PSTricks: post script support, no support for pdflatex, but ps2pdf, The most powerful.
   3. The practical choice of your figures
      - Matlab Figures: Matfig2pgf can be used to convert .fig to .pgf or .tkiz
      - Inkscape Dias: Plugins of Inkscape to convert Inkscape to .tkiz
      - Dia Charts: Directly convert to .tkiz format, and easiliy adapt the size of the charts with du in the regenrated .tkiz files
      - For simple figures: one can code them directly by tkiz or pgf script
      - Eps Figures: Eps files can be directly converted to .pgf by eps2pgf library
      - The latex /resizebox{0.9/columnwidth}{!}{you inputed figure}

        
** COMMENT Beamer in Lyx
   1. One Frame has several slides to control the animation and overlays
   2. \altert{} is similar to the \emph, the \alert command needs to be entered in TEX-mode, which is awkward. It’s easier to just paint the text in red.
   3. \pause will pause and wait another item
   4. \uncover<3>{content} this means uncover the content for a specified slides, but on all other slides, it still occupies the sapces
   5. \only<3>{content} is similar to \uncover, but without occupation of its spaces on the other slides
   6. For the following commands, adding an overlay specification causes the command to be simply ignored on slides that are not included in the specification: \textbf, \textit, \textsl, \textrm, \textsf, \color, \alert, \structure.
#+begin_src latex
  \begin{frame}
    \color<2-3>[rgb]{1,0,0} This text is red on slides 2 and 3, otherwise black.
  \end{frame}
#+end_src
   1. \visible and \invisible are similar to \only
   2. \alt<2>{On Slide 2}{Not on slide 2.} a set and its alternative
   3. \temporal, see below
      \temporal<3-4>{Shown on 1, 2}{Shown on 3, 4}{Shown 5, 6, 7, ...}
      \temporal<3,5>{Shown on 1, 2, 4}{Shown on 3, 5}{Shown 6, 7, 8, ...}
   4. If in the ordinary article document, you want to use the .tikz file but without removeing all the overlap specifications, you just need to include the beamerarticle in your preamble, e.g. \usepackage{beamerarticle}. With the help of this package, all the beamer overlap specifications commands will be suppressed, since we are in beamerarticle mode but beamer presentation mode.
   5. Note that the different between \inlcudegraphcs{}<2->  and \visible<2->{\inlcudegraphcs{}}, the later one will still occupy the space if it is not shown.
   6. in many commands, you can directly use <3-> or <3,4,5>, etc. They means only<3-> and only<3,4,5> respectively.
   7. Before Items you can add <alert@1>,<2-| alert@2-8>,<9-| alert@9>,<only@-9| visible@8->,<only@10->
   8. \begin{actionenv}<2-| alert@3-4,6> This text is shown the same way as the text below. \end{actionenv}
   9. \action<alert@2>{Could also have used \alert<2>{}.}
   10. \item<2-| alert@2-3>
   11. \beamerpauses the current value of the Latex counter beamerpauses, which is 1 at the beginning of the frame
   12. Economic Writings
#+begin_src latex
  \begin{itemize}[<+-| alert@+>]
  \item Apple
  \item Peach
  \item Plum
  \item Orange
  \end{itemize}
#+end_src
  1. Any occurence of a +-sign may be followed by an offset in round brackets. This offset will be added to the value of beamerpauses. Thus, if beamerpauses is 2, then <+(1)-> expands to <3-> and <+(-1)-+> expands to <1-2>
  2. 
